name: CD Pipeline Back

on:
  workflow_run:
    workflows: ["CI Pipeline Back"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull titeshi/deepsee-back:latest

      - name: Delete Old docker container
        run: sudo docker rm -f deepsee-back-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name deepsee-back-container titeshi/deepsee-back
